/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppMeasureRouteImport } from './routes/_app.measure'
import { Route as AppRadarRouteImport } from './routes/_app.radar'
import { Route as AppReconRouteImport } from './routes/_app.recon'
import { Route as AppEstimatesIndexRouteImport } from './routes/_app.estimates.index'
import { Route as AppEstimatesEstimateIdRouteImport } from './routes/_app.estimates.$estimateId'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app.properties.index'
import { Route as AppPropertiesPropertyIdRouteImport } from './routes/_app.properties.$propertyId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMeasureRoute = AppMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppReconRoute = AppReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatesIndexRoute = AppEstimatesIndexRouteImport.update({
  id: '/estimates/',
  path: '/estimates/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatesEstimateIdRoute = AppEstimatesEstimateIdRouteImport.update({
  id: '/estimates/$estimateId',
  path: '/estimates/$estimateId',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesPropertyIdRoute = AppPropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/leads': typeof AppLeadsRoute
  '/marketing': typeof AppMarketingRoute
  '/measure': typeof AppMeasureRoute
  '/radar': typeof AppRadarRoute
  '/recon': typeof AppReconRoute
  '/estimates/$estimateId': typeof AppEstimatesEstimateIdRoute
  '/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/estimates/': typeof AppEstimatesIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/leads': typeof AppLeadsRoute
  '/marketing': typeof AppMarketingRoute
  '/measure': typeof AppMeasureRoute
  '/radar': typeof AppRadarRoute
  '/recon': typeof AppReconRoute
  '/': typeof AppIndexRoute
  '/estimates/$estimateId': typeof AppEstimatesEstimateIdRoute
  '/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/estimates': typeof AppEstimatesIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/leads': typeof AppLeadsRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/measure': typeof AppMeasureRoute
  '/_app/radar': typeof AppRadarRoute
  '/_app/recon': typeof AppReconRoute
  '/_app/': typeof AppIndexRoute
  '/_app/estimates/$estimateId': typeof AppEstimatesEstimateIdRoute
  '/_app/properties/$propertyId': typeof AppPropertiesPropertyIdRoute
  '/_app/estimates/': typeof AppEstimatesIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/marketing'
    | '/measure'
    | '/radar'
    | '/recon'
    | '/estimates/$estimateId'
    | '/properties/$propertyId'
    | '/estimates/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/leads'
    | '/marketing'
    | '/measure'
    | '/radar'
    | '/recon'
    | '/'
    | '/estimates/$estimateId'
    | '/properties/$propertyId'
    | '/estimates'
    | '/properties'
  id:
    | '__root__'
    | '/_app'
    | '/_app/leads'
    | '/_app/marketing'
    | '/_app/measure'
    | '/_app/radar'
    | '/_app/recon'
    | '/_app/'
    | '/_app/estimates/$estimateId'
    | '/_app/properties/$propertyId'
    | '/_app/estimates/'
    | '/_app/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/measure': {
      id: '/_app/measure'
      path: '/measure'
      fullPath: '/measure'
      preLoaderRoute: typeof AppMeasureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radar': {
      id: '/_app/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recon': {
      id: '/_app/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof AppReconRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estimates/': {
      id: '/_app/estimates/'
      path: '/estimates'
      fullPath: '/estimates/'
      preLoaderRoute: typeof AppEstimatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estimates/$estimateId': {
      id: '/_app/estimates/$estimateId'
      path: '/estimates/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof AppEstimatesEstimateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/$propertyId': {
      id: '/_app/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMeasureRoute: typeof AppMeasureRoute
  AppRadarRoute: typeof AppRadarRoute
  AppReconRoute: typeof AppReconRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEstimatesEstimateIdRoute: typeof AppEstimatesEstimateIdRoute
  AppPropertiesPropertyIdRoute: typeof AppPropertiesPropertyIdRoute
  AppEstimatesIndexRoute: typeof AppEstimatesIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeadsRoute: AppLeadsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMeasureRoute: AppMeasureRoute,
  AppRadarRoute: AppRadarRoute,
  AppReconRoute: AppReconRoute,
  AppIndexRoute: AppIndexRoute,
  AppEstimatesEstimateIdRoute: AppEstimatesEstimateIdRoute,
  AppPropertiesPropertyIdRoute: AppPropertiesPropertyIdRoute,
  AppEstimatesIndexRoute: AppEstimatesIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
